### ISSUE TITLE
SpeechLM：KeyError: 'text_transformer' while initing the SpeechLMConfig

### ISSUE THREAD

**Issue by guokr233** [microsoft/SpeechT5#26]
Hi，I'm trying to use the script in README to Extract features using pre-trained models, I used the model  speechlmp_base_asr_checkpoint_best.pt.But I encountered an error while initing the SpeechLMConfig：
> Traceback (most recent call last):
  File "/remote-home/jzhan/SpeechT5/SpeechLM/test.py", line 7, in <module>
    cfg = SpeechLMConfig(checkpoint['cfg']['model'])
  File "/SpeechT5/SpeechLM/SpeechLM.py", line 128, in __init__
    self.update(cfg)
  File "/SpeechT5/SpeechLM/SpeechLM.py", line 132, in update
    self.text_transformer = TransformerConfig(model_cfg['text_transformer'])
KeyError: 'text_transformer'

Am I missing any model files?

**Comment by zz12375** [comment]
Hello, @guokr233 
For now, only pre-trained models could be directly used to extract features, you have 3 choices of the model as the readme provided,
![image](https://user-images.githubusercontent.com/29814033/205150950-9f295b63-3c0d-4744-a2bb-7f8927d0ead8.png)
While the one you used, `speechlmp_base_asr_checkpoint_best.pt`, is a fine-tuned ASR model, which can not be directly loaded by `SpeechT5/SpeechLM/SpeechLM.py`.

- The configuration descriptions saved in checkpoints are different between pre-trained models and fine-tuned models, that's why you got this error when loading fine-tuned models. 

- What's the difference between the models listed in the above figure and the models listed in the **Pre-Trained and Fine-tuned Models** Table? The 3 models listed in the above figure are made from the original checkpoints by copying parameters and removing unused modules.

Hope the above information helps you.

**Comment by guokr233** [comment]
I used the model mentioned in "Extract features using pre-trained models"，it worked，thank you very much！
