### ISSUE TITLE
SpeechUT inference and fine-tune problem

### ISSUE THREAD

**Issue by ytf-philp** [microsoft/SpeechT5#34]
I want to use the released version of pretrained SpeechUT model to fine tune and also want to use the released fine-tuned model on MUST-C ende model to inference, however when i reload the checkpoints, there are some extra non-local path which caused "FileNotFoundError", how can i solve this problem?
![image](https://user-images.githubusercontent.com/54100491/218961435-794b7b06-7d1b-4c34-ae1e-b72418b8c876.png)

**Comment by zz12375** [comment]
Hi @ytf-philp , I think I have fixed the bug. 
1. For now, the code will default to load the dictionaries from the checkpoint, instead of asking for no-existing config files (*.yaml).
2. I still added the `config.yaml` (no needed anymore for fine-tuning/inference, but still needed for pre-training) to `dataset/MuSTC/en_{de,es,fr}/`, just for a look.
3. When inference,  [`inference_st.sh`](https://github.com/microsoft/SpeechT5/blob/main/SpeechUT/speechut/scripts/tune_speechut_st/inference_st.sh) will still ask for the pre-trained model which may cause a *FileNotFoundError*, to prevent it, use `--model-overrides "{'model':{'w2v_path':'/path/to/your/pretrained/model.pt'}}"` in  [`inference_st.sh`](https://github.com/microsoft/SpeechT5/blob/main/SpeechUT/speechut/scripts/tune_speechut_st/inference_st.sh). Click [here](https://github.com/microsoft/SpeechT5/blob/main/SpeechUT/speechut/scripts/tune_speechut_st/inference_st.sh#L40) to see the usage.

Hope the above information helps, and thank you for your feedback.

**Comment by ytf-philp** [comment]
Thank you, this bug has been fixed. @zz12375
