### ISSUE TITLE
soundfile.LibsndfileError: <exception str() failed>

### ISSUE THREAD

**Issue by ciwei6107563** [microsoft/SpeechT5#84]
When I was trying to run WavLLM on the CPU, after completing all the operations according to the readme, I encountered an error called soundfile LibsndfileError:<exception str()failed>  using the command bash examples/wavellm/scripts/inference_stft. sh my_madel_sth emo , how can I fix this?

**Comment by cdd1993** [comment]
@ciwei6107563 I also encountered this problem, how did you solve it? Thanks.

**Comment by ovaisiqbalshah** [comment]
How did you resolve this issue.

**Comment by morrisalp** [comment]
The error message was more clear when avoiding multiprocessing (in the python call in `inference_sft.sh`, add flags (`--num-workers 0 --data-buffer-size 1`), which showed an audio file path not leading to a valid audio file.

That showed the problem was the audio path in the `.tsv` file (e.g. `SQQA.tsv` for the SQQA path). Since I was calling inference inside the fairseq directory, I had to remove the prefix `SpeechT5/WavLLM/fairseq/`.

This assumes the audio files in `test_data/audio` are all not corrupted.
